name = "ErdosUnitDistance"
defaultTargets = ["ErdosUnitDistance"]

[[require]]
name = "PrimeNumberTheoremAnd"
git = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd.git"
rev = "47fa48680663df41146704d02a5b092d792bd5b9"

[[require]]
name = "TauCeti"
git = "https://github.com/FormalFrontier/TauCeti"
rev = "278ce66c349a60e7f96489c26b6d611be277f921"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.2"

[[lean_lib]]
name = "ErdosUnitDistance"
