name = "ErdosUnitDistance"
defaultTargets = ["ErdosUnitDistance"]

[[require]]
name = "PrimeNumberTheoremAnd"
git = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd.git"

[[lean_lib]]
name = "ErdosUnitDistance"
