import Mathlib

/-!
# Bridge: square-class descent ⟹ `Kf_finrank`

Fallback decomposition for the multiquadratic-degree theorem
`Module.finrank ℚ (Kf g) = 2 ^ (g + 1)`, assuming the square-class
descent kernel of `SquareClassDescent.lean`.  Steps:

* `q3_not_squareClass`: a prime `≡ 3 mod 4` is not a square times a
  product of smaller such primes (`padicValRat` parity at `q3 n`).
* `sqrt_q3_notMem_tower`: hence `√(q3 n) ∉ ℚ(√q3 0, …, √q3 (n-1))`
  (descent kernel + previous step).
* `sqrtTower_finrank`: the real tower has degree `2^n` (induction;
  each step is a degree-2 simple extension since `X² - q3 n` has no
  root by the previous step).
* `Kf_finrank`: complexify (`IntermediateField.map` along
  `Complex.ofRealHom`, which preserves `finrank`), identify `Kf g` with
  `(complexified tower) ⊔ ℚ(i)`, and double the degree once more since
  `X² + 1` has no root in a subfield of `ℝ`'s image.

The statements below are sorried; they are exact targets for
Aristotle/Codex once `SquareClassDescent.lean` is complete.
-/

namespace Erdos

open IntermediateField

noncomputable def q3 (j : ℕ) : ℕ := Nat.nth (fun n => n.Prime ∧ n % 4 = 3) j

theorem infinite_setOf_q3 : {n | n.Prime ∧ n % 4 = 3}.Infinite := by
  have h : {p : ℕ | p.Prime ∧ p ≡ 3 [MOD 4]}.Infinite :=
    Nat.infinite_setOf_prime_and_modEq (by norm_num) (by decide)
  convert h using 2 with n

theorem q3_spec (j : ℕ) : (q3 j).Prime ∧ q3 j % 4 = 3 :=
  Nat.nth_mem_of_infinite infinite_setOf_q3 j

theorem q3_strictMono : StrictMono q3 :=
  Nat.nth_strictMono infinite_setOf_q3

noncomputable def sqrtTower (c : ℕ → ℚ) (n : ℕ) : IntermediateField ℚ ℝ :=
  IntermediateField.adjoin ℚ ((fun j => Real.sqrt (c j)) '' Set.Iio n)

/-- Square-class descent (proved in `SquareClassDescent.lean`; restated
here to keep this file self-contained). -/
theorem squareClass_of_sqrt_mem (c : ℕ → ℚ) (hc : ∀ j, 0 < c j) :
    ∀ n, ∀ r : ℚ, 0 < r → (Real.sqrt r : ℝ) ∈ sqrtTower c n →
      ∃ (T : Finset ℕ) (s : ℚ), ↑T ⊆ Set.Iio n ∧
        r = s ^ 2 * ∏ j ∈ T, c j := by
  sorry

/-- [valuation parity]  A prime is not a rational square times a product
of distinct other primes: compare `padicValRat (q3 n)` of both sides —
odd on the left, even on the right (`s²` contributes evenly, the distinct
primes contribute `0`). -/
theorem q3_not_squareClass (n : ℕ) (T : Finset ℕ) (hT : ↑T ⊆ Set.Iio n)
    (s : ℚ) : ((q3 n : ℚ)) ≠ s ^ 2 * ∏ j ∈ T, ((q3 j : ℚ)) := by
  sorry

/-- `√(q3 n)` does not lie in the tower generated by the earlier square
roots (descent + valuation parity). -/
theorem sqrt_q3_notMem_tower (n : ℕ) :
    (Real.sqrt (q3 n) : ℝ) ∉ sqrtTower (fun j => (q3 j : ℚ)) n := by
  intro hmem
  obtain ⟨T, s, hT, heq⟩ :=
    squareClass_of_sqrt_mem (fun j => (q3 j : ℚ))
      (fun j => by exact_mod_cast (q3_spec j).1.pos) n (q3 n)
      (by exact_mod_cast (q3_spec n).1.pos) hmem
  exact q3_not_squareClass n T hT s heq

/-- [tower induction]  The real multiquadratic tower has full degree:
each step adjoins a root of the irreducible (no root, degree 2)
polynomial `X² - q3 n`. -/
theorem sqrtTower_finrank (n : ℕ) :
    Module.finrank ℚ (sqrtTower (fun j => (q3 j : ℚ)) n) = 2 ^ n := by
  sorry

/-- The multiquadratic CM field (must match `Framework.lean` verbatim). -/
noncomputable def Kf (g : ℕ) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ
    (insert Complex.I ((fun j => ((Real.sqrt (q3 j) : ℝ) : ℂ)) '' Set.Iio g))

/-- [complexify and adjoin `i`]  `Kf g` has degree `2^(g+1)`:
the `ℚ`-algebra map `Complex.ofRealHom` carries `sqrtTower` to an
isomorphic intermediate field of `ℂ` generated by the `(√q3 j : ℂ)`
(`IntermediateField.adjoin_map`); `Kf g` is its sup with `ℚ(i)`
(`adjoin_insert`), and `X² + 1` has no root in the (real-valued) image,
so the degree doubles once more. -/
theorem Kf_finrank (g : ℕ) : Module.finrank ℚ (Kf g) = 2 ^ (g + 1) := by
  sorry

end Erdos
